version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "gradle-twirl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "maven-twirl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "1.6.x"
    commit-message:
      prefix: "[1.6.x] "
